### ISSUE TITLE
Socket IO Connection to C#

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/ggb-connect-server#1]
For the socket, we get an error server side each time a message is attempted to send through socket.io . See here:
https://pastebin.com/jk1jHgzQ
The unexpected token is the object name of whatever is updated. This prevents any message from being received on our end.

**Comment by camden-bock** [comment]
```
 2019-07-01T14:19:44.237+00:00, (1561990784237:cb34fdc6dfe0:35:jxkgz872:10000) [response] http://cb34fdc6dfe0:8080: get /handshake {"sessionId":"2ebeeafc-edd1-4ebf-8ca4-e34dcc269f4d","version":"1234321"} 200 (2113ms)
web_1  | (node:35) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token B in JSON at position 0
web_1  |     at JSON.parse (<anonymous>)
web_1  |     at Page._onBindingCalled (/webapp/node_modules/puppeteer/lib/Page.js:512:36)
web_1  |     at CDPSession.<anonymous> (/webapp/node_modules/puppeteer/lib/Page.js:122:54)
web_1  |     at CDPSession.emit (events.js:200:13)
web_1  |     at CDPSession._onMessage (/webapp/node_modules/puppeteer/lib/Connection.js:200:12)
web_1  |     at Connection._onMessage (/webapp/node_modules/puppeteer/lib/Connection.js:112:17)
web_1  |     at WebSocket.<anonymous> (/webapp/node_modules/puppeteer/lib/WebSocketTransport.js:41:24)
web_1  |     at WebSocket.onMessage (/webapp/node_modules/puppeteer/node_modules/ws/lib/event-target.js:120:16)
web_1  |     at WebSocket.emit (events.js:200:13)
web_1  |     at Receiver.receiverOnMessage (/webapp/node_modules/puppeteer/node_modules/ws/lib/websocket.js:789:20)
web_1  | (node:35) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
web_1  | (node:35) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
web_1  | 2019-07-01T14:19:44.254+00:00, (1561990784254:cb34fdc6dfe0:35:jxkgz872:10001) [response] http://cb34fdc6dfe0:8080: post /command {} 200 (3195ms)
```

**Comment by nsgnn** [comment]
The issue is reproducible when we attempt to send an object update through the socket setup. It errors with an unexpected token that corresponds to the name of the object that was updated. This should be a string with that name, but it attempts to find a label associated with the ggb (GeoGebra) objects name. For example, the sample output above shows an unexpected token `B`. This should just be the string literal of `"B"`.

**Comment by camden-bock** [comment]
@nsgnn can you provide a detailed protocol for reproducing the error?

**Comment by nsgnn** [comment]
Syntax of object declaration for GGB is as follows. `ObjName = (X, Y, Z)` for a dynamic point. When declared with `ObjName:Point({X,Y,Z})`, objects do not produce update event calls. The [output](https://i.imgur.com/oOviUWl.png) is produced using the demo script [here](https://gist.github.com/nsgnn/84db61a2bbd6cc6c931923c57349fa81).

**Comment by nsgnn** [comment]
Tested C# Socket.io clients:

- [Websocket Sharp](https://github.com/sta/websocket-sharp)
  - Doesn't contain on(event, action) or emit(string, args[])
- [Socket.io-unity](https://github.com/floatinghotpot/socket.io-unity)
  - Doesn't contain on(event, action) or emit(string, args[])
- [SocketIoClientDotNet](https://github.com/Quobject/SocketIoClientDotNet)
  - Breaks packages.
- [UnitySocketIO](https://github.com/NetEase/UnitySocketIO)
  - Breaks packages.

**Comment by nsgnn** [comment]
Unity connects to the websocket and does a nice ping/pong back and forth. It does not recieve the event emissions though. This might be due to something on our end, as I can see the events on the typescript version of the socket test script.
